# 服务
server:
  host: localhost
  port: 8081

# mysql
datasource:
  driverName: mysql
  host: 1.15.189.106
  port: 3306
  database: library
  username: root
  password: Root123.
  charset: utf8
  loc: Asia/Shanghai

# redis
redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  poolSize: 100

# rabbitmq
rabbitmq:
  host: 1.15.189.106
  port: 5672
  username: admin
  password: admin
  virtual-host: /



# 分页查询
page:
  pageSize: 10
  pageNumber: 1

# file
file:
  path: /Users/huangsn/Desktop/images
  Url: http://1.15.189.106:9050
  library: http://1.15.189.106:9050/imageLibrary